Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision "file", source: "./config", destination: "/home/vagrant/config"
  config.vm.provision "file", source: "./examples", destination: "/home/vagrant/examples"

  config.vm.provision "shell" do |s|
      s.path = "provisioning.sh"
  end
end
